$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: "en,en-US"
useGitignore: true
minWordLength: 4
import:
    - ".cspell/rust/cspell-ext.json"
dictionaryDefinitions:
    - name: project-words
      path: .cspell/project-words.txt
      addWords: true
dictionaries:
    - project-words
ignorePaths:
    - .cspell
    - target
    - crates/allocator
    - Cargo.lock
    - Cargo.toml
